import AdmZip from 'adm-zip';
import fs from 'node:fs/promises';
import path from 'node:path';
import type {
  CreateWorkbenchModuleRequest,
  PluginManifest,
  WorkbenchModuleResult,
  WorkbenchTemplate
} from '../shared/types';
import { ensureWorkspace, getModsRoot, openModsFolder } from './persistence';

const templates: WorkbenchTemplate[] = [
  {
    language: 'javascript',
    label: 'JavaScript',
    description: 'ES module with a simple execute function.',
    entry: 'src/index.js'
  },
  {
    language: 'typescript',
    label: 'TypeScript',
    description: 'Typed ES module with a minimal tsconfig.',
    entry: 'src/index.ts'
  },
  {
    language: 'java',
    label: 'Java',
    description: 'Java 17 Gradle application module.',
    entry: 'src/main/java/module/ExtensionModule.java'
  },
  {
    language: 'kotlin',
    label: 'Kotlin',
    description: 'Kotlin/JVM Gradle application module.',
    entry: 'src/main/kotlin/module/ExtensionModule.kt'
  }
];

function sanitizeId(raw: string): string {
  return raw
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 64);
}

function sourceTemplate(language: WorkbenchTemplate['language'], id: string): string {
  if (language === 'java') {
    return `package module;\n\npublic final class ExtensionModule {\n    public String execute(String input) {\n        return "{\\"plugin\\":\\"${id}\\",\\"status\\":\\"ok\\"}";\n    }\n}\n`;
  }
  if (language === 'kotlin') {
    return `package module\n\nclass ExtensionModule {\n    fun execute(input: String): String = "{\\"plugin\\":\\"${id}\\",\\"status\\":\\"ok\\"}"\n}\n`;
  }
  if (language === 'typescript') {
    return `export interface ModuleResult {\n  plugin: string;\n  status: 'ok';\n  input: unknown;\n}\n\nexport function execute(input: unknown): ModuleResult {\n  return { plugin: '${id}', status: 'ok', input };\n}\n`;
  }
  return `export function execute(input) {\n  return { plugin: '${id}', status: 'ok', input };\n}\n`;
}

function buildSpec(language: WorkbenchTemplate['language'], id: string): PluginManifest['build'] {
  if (language === 'java' || language === 'kotlin') {
    return {
      command: 'gradle',
      args: ['build'],
      output: 'build/libs',
      notes: `${language} module generated by the Discord Extensions workbench.`
    };
  }
  if (language === 'typescript') {
    return {
      command: 'npx',
      args: ['tsc', '--noEmit'],
      notes: 'Type-check the module before packaging.'
    };
  }
  return undefined;
}

export class WorkbenchManager {
  public listTemplates(): WorkbenchTemplate[] {
    return templates.map((template) => ({ ...template }));
  }

  public async createModule(request: CreateWorkbenchModuleRequest): Promise<WorkbenchModuleResult> {
    await ensureWorkspace();
    const id = sanitizeId(request.id);
    if (!id || !request.name.trim()) {
      throw new Error('Module ID and name are required.');
    }

    const template = templates.find((item) => item.language === request.language);
    if (!template) {
      throw new Error('Unsupported workbench language.');
    }

    const modulePath = path.join(getModsRoot(), id);
    await fs.rm(modulePath, { recursive: true, force: true });
    await fs.mkdir(modulePath, { recursive: true });

    const manifest: PluginManifest = {
      id,
      name: request.name.trim(),
      version: '1.0.0',
      description: request.description.trim() || 'Extension module created with Discord Extensions workbench.',
      author: request.author.trim() || 'Unknown',
      category: request.category,
      entry: template.entry,
      permissions: ['ui-panel', 'settings-persistence'],
      settings: [],
      hostKind: 'tool',
      language: request.language,
      build: buildSpec(request.language, id)
    };

    const manifestPath = path.join(modulePath, 'plugin.json');
    const entryPath = path.join(modulePath, template.entry);
    await fs.mkdir(path.dirname(entryPath), { recursive: true });
    await fs.writeFile(manifestPath, JSON.stringify(manifest, null, 2), 'utf8');
    await fs.writeFile(entryPath, sourceTemplate(request.language, id), 'utf8');
    await fs.writeFile(
      path.join(modulePath, 'README.md'),
      `# ${manifest.name}\n\nGenerated by Discord Extensions Module Workbench.\n\n- ID: \`${id}\`\n- Language: \`${request.language}\`\n- Entry: \`${template.entry}\`\n`,
      'utf8'
    );

    if (request.language === 'typescript') {
      await fs.writeFile(
        path.join(modulePath, 'tsconfig.json'),
        JSON.stringify({ compilerOptions: { target: 'ES2022', module: 'ESNext', strict: true }, include: ['src/**/*.ts'] }, null, 2),
        'utf8'
      );
    }

    if (request.language === 'java' || request.language === 'kotlin') {
      await fs.writeFile(path.join(modulePath, 'settings.gradle.kts'), `rootProject.name = "${id}"\n`, 'utf8');
      const pluginLine = request.language === 'kotlin'
        ? 'kotlin("jvm") version "2.0.21"'
        : 'java';
      await fs.writeFile(
        path.join(modulePath, 'build.gradle.kts'),
        `plugins {\n    ${pluginLine}\n}\n\nrepositories { mavenCentral() }\n\njava { toolchain { languageVersion.set(JavaLanguageVersion.of(17)) } }\n`,
        'utf8'
      );
    }

    return { id, modulePath, manifestPath, entryPath };
  }

  public async exportModule(moduleId: string, targetPath: string): Promise<string> {
    const id = sanitizeId(moduleId);
    const modulePath = path.join(getModsRoot(), id);
    const stat = await fs.stat(modulePath).catch(() => null);
    if (!stat?.isDirectory()) {
      throw new Error('Module directory does not exist.');
    }
    const archive = new AdmZip();
    archive.addLocalFolder(modulePath, id);
    archive.writeZip(targetPath);
    return targetPath;
  }

  public async openModsFolder(): Promise<string> {
    return openModsFolder();
  }
}
