package io.yanagikh.discordextensions

import android.os.Bundle
import android.widget.ArrayAdapter
import android.widget.Toast
import androidx.activity.result.contract.ActivityResultContracts
import androidx.appcompat.app.AppCompatActivity
import io.yanagikh.discordextensions.databinding.ActivityWorkbenchBinding
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import java.io.FileInputStream
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

class WorkbenchActivity : AppCompatActivity() {
    private lateinit var binding: ActivityWorkbenchBinding
    private var lastModuleDirectory: File? = null

    private val exportLauncher = registerForActivityResult(ActivityResultContracts.CreateDocument("application/zip")) { uri ->
        val moduleDirectory = lastModuleDirectory ?: return@registerForActivityResult
        if (uri == null) return@registerForActivityResult
        runCatching {
            contentResolver.openOutputStream(uri).use { output ->
                requireNotNull(output) { "Unable to open export destination." }
                ZipOutputStream(output).use { zip ->
                    moduleDirectory.walkTopDown().filter { it.isFile }.forEach { file ->
                        val relative = file.relativeTo(moduleDirectory).invariantSeparatorsPath
                        zip.putNextEntry(ZipEntry("${moduleDirectory.name}/$relative"))
                        FileInputStream(file).use { input -> input.copyTo(zip) }
                        zip.closeEntry()
                    }
                }
            }
        }.onSuccess {
            Toast.makeText(this, R.string.module_exported, Toast.LENGTH_SHORT).show()
            DebugLogStore.append(this, "Exported module ${moduleDirectory.name}")
        }.onFailure { error ->
            binding.workbenchStatusText.text = error.message
            DebugLogStore.append(this, "Module export failed: ${error.message}")
        }
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityWorkbenchBinding.inflate(layoutInflater)
        setContentView(binding.root)

        val languages = listOf("javascript", "typescript", "java", "kotlin")
        binding.languageSpinner.adapter = ArrayAdapter(this, android.R.layout.simple_spinner_dropdown_item, languages)
        binding.authorInput.setText("YanagiKH")

        binding.createModuleButton.setOnClickListener { createModule() }
        binding.exportModuleButton.setOnClickListener {
            val directory = lastModuleDirectory ?: return@setOnClickListener
            exportLauncher.launch("${directory.name}.zip")
        }
        binding.backButton.setOnClickListener { finish() }
    }

    private fun createModule() {
        val id = sanitizeId(binding.moduleIdInput.text.toString())
        val name = binding.moduleNameInput.text.toString().trim()
        val author = binding.authorInput.text.toString().trim().ifEmpty { "Unknown" }
        val description = binding.descriptionInput.text.toString().trim().ifEmpty { "Extension module created with the Android workbench." }
        val language = binding.languageSpinner.selectedItem.toString()

        if (id.isEmpty() || name.isEmpty()) {
            Toast.makeText(this, R.string.invalid_module, Toast.LENGTH_SHORT).show()
            return
        }

        runCatching {
            val root = File(filesDir, "mods/$id")
            root.deleteRecursively()
            root.mkdirs()

            val entry = when (language) {
                "java" -> "src/main/java/module/ExtensionModule.java"
                "kotlin" -> "src/main/kotlin/module/ExtensionModule.kt"
                "typescript" -> "src/index.ts"
                else -> "src/index.js"
            }
            val manifest = JSONObject()
                .put("id", id)
                .put("name", name)
                .put("version", "1.0.0")
                .put("description", description)
                .put("author", author)
                .put("category", "utility")
                .put("entry", entry)
                .put("permissions", JSONArray().put("ui-panel").put("settings-persistence"))
                .put("settings", JSONArray())
                .put("hostKind", "tool")
                .put("language", language)

            File(root, "plugin.json").writeText(manifest.toString(2))
            val source = File(root, entry)
            source.parentFile?.mkdirs()
            source.writeText(template(language, id))
            File(root, "README.md").writeText("# $name\n\n$id module generated by Discord Extensions Android workbench.\n")

            lastModuleDirectory = root
            binding.exportModuleButton.isEnabled = true
            binding.workbenchStatusText.text = "${getString(R.string.module_created)}\n${root.absolutePath}"
            DebugLogStore.append(this, "Created module $id language=$language")
        }.onFailure { error ->
            binding.workbenchStatusText.text = error.message
            DebugLogStore.append(this, "Module creation failed: ${error.message}")
        }
    }

    private fun sanitizeId(raw: String): String = raw
        .trim()
        .lowercase()
        .replace(Regex("[^a-z0-9._-]+"), "-")
        .trim('-')
        .take(64)

    private fun template(language: String, id: String): String = when (language) {
        "java" -> """package module;

public final class ExtensionModule {
    public String execute(String input) {
        return "{\"plugin\":\"$id\",\"status\":\"ok\"}";
    }
}
"""
        "kotlin" -> """package module

class ExtensionModule {
    fun execute(input: String): String = "{\"plugin\":\"$id\",\"status\":\"ok\"}"
}
"""
        "typescript" -> """export function execute(input: unknown) {
  return { plugin: '$id', status: 'ok', input };
}
"""
        else -> """export function execute(input) {
  return { plugin: '$id', status: 'ok', input };
}
"""
    }
}
